# Generated by Django 4.2.30 on 2026-07-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('annual_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eligibility', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
            ],
            options={
                'ordering': ['course_name'],
            },
        ),
    ]
